# Generated by Django 4.2.1 on 2023-05-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='spot',
            field=models.CharField(choices=[('1', '고양점'), ('2', '대구점'), ('3', '세종점'), ('4', '양주점'), ('5', '포항점')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
