# Generated by Django 4.2.1 on 2023-05-09 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_basicuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BasicUser',
        ),
    ]
