# Generated by Django 4.2.1 on 2023-05-09 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_basicuser_basic_user_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='basicuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='basicuser',
            name='password',
        ),
    ]
