# Generated by Django 4.2.1 on 2023-05-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_adminuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
