# Generated by Django 4.2.1 on 2023-05-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_adminuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='is_staff',
        ),
        migrations.AddField(
            model_name='adminuser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
    ]
