# Generated by Django 4.2.1 on 2023-05-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookset', to='hotels.rooms'),
        ),
    ]
